# Generated by Django 5.0.7 on 2024-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_role_alter_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='teacher', max_length=10),
        ),
    ]
